In [ ]:
import os
import numpy as np
import librosa
import sounddevice as sd
import tensorflow as tf
import tensorflow_hub as hub
import threading
import cv2
from scipy.io.wavfile import write
from scipy.signal import butter, lfilter
from ultralytics import YOLO
from datetime import datetime
from deepface import DeepFace
from sklearn.metrics.pairwise import cosine_similarity
# === Model Loading ===
yolo_model_path = 'yolo_v2.pt'  # YOLO model path

# Load models
audio_model = tf.keras.models.load_model("best_model.keras")
yamnet_model = hub.load('https://www.kaggle.com/models/google/yamnet/TensorFlow2/yamnet/1')
yolo_model = YOLO(yolo_model_path)

# Ensure required directories exist
os.makedirs("anomalous_videos", exist_ok=True)
os.makedirs("anomalous_audio", exist_ok=True)
os.makedirs("unknown_faces", exist_ok=True)

# Index-to-label mapping for YAMNet
index_to_label = {
    0: "Emergency_alert_sound",
    1: "Explosions",
    2: "Gunshots",
    3: "Human screams",
    4: "Bottles breaking",
    5: "Dog bark",
    # 6: "Human Conversation",
    # Add more labels as per your trained model
}

# Noise reduction using a Butterworth filter
def butter_bandpass(lowcut, highcut, fs, order=5):
    nyquist = 0.5 * fs
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = butter(order, [low, high], btype='band')
    return b, a

def bandpass_filter(data, lowcut=300.0, highcut=3400.0, fs=16000, order=5):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = lfilter(b, a, data)
    return y

# Preprocess and generate YAMNet embeddings
def preprocess_audio(audio_waveform, target_length=16000 * 5):
    # Apply noise reduction
    audio_waveform = bandpass_filter(audio_waveform)

    # Pad or truncate the waveform to the target length
    if len(audio_waveform) < target_length:
        audio_waveform = np.pad(audio_waveform, (0, target_length - len(audio_waveform)))
    else:
        audio_waveform = audio_waveform[:target_length]

    # Normalize between -1 and 1
    audio_waveform = audio_waveform.astype(np.float32)
    audio_waveform /= np.max(np.abs(audio_waveform))
    return audio_waveform

def predict_audio_from_stream(audio_data, sr, confidence_threshold=0.7):
    processed_audio = preprocess_audio(audio_data)
    _, yamnet_embeddings, _ = yamnet_model(processed_audio)
    avg_embedding = tf.reduce_mean(yamnet_embeddings, axis=0).numpy().reshape(1, -1)

    prediction = audio_model.predict(avg_embedding)
    predicted_class_index = np.argmax(prediction, axis=1)[0]
    confidence = prediction[0][predicted_class_index]

    if confidence >= confidence_threshold:
        predicted_class_name = index_to_label.get(predicted_class_index, "Unknown")
        return predicted_class_name, confidence
    return "Unknown", confidence

# Audio capturing and processing thread
def process_audio_stream(duration=5, sample_rate=16000):
    print("[INFO] Starting audio detection thread...")
    while True:
        print("[INFO] Recording audio...")
        audio_data = sd.rec(int(duration * sample_rate), samplerate=sample_rate, channels=1, dtype='float32')
        sd.wait()  # Wait until the recording is finished
        audio_data = audio_data.flatten()

        predicted_class, confidence = predict_audio_from_stream(audio_data, sample_rate)

        if predicted_class != "Unknown":
            print(f"[{datetime.now()}] Detected audio anomaly: {predicted_class} (Confidence: {confidence:.2f})")
            audio_filename = f"anomalous_audio/{predicted_class}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.wav"
            write(audio_filename, sample_rate, (audio_data * 32767).astype(np.int16))
            print(f"[INFO] Audio saved to: {audio_filename}")

# Face recognition setup
known_faces_dir = "known_faces"
os.makedirs(known_faces_dir, exist_ok=True)
known_encodings = []
known_names = []

# Load known faces
def load_known_faces():
    for name in os.listdir(known_faces_dir):
        person_dir = os.path.join(known_faces_dir, name)
        if not os.path.isdir(person_dir):
            continue

        for file in os.listdir(person_dir):
            file_path = os.path.join(person_dir, file)
            try:
                encoding = DeepFace.represent(img_path=file_path, model_name='Facenet')[0]['embedding']
                known_encodings.append(encoding)
                known_names.append(name)
            except Exception as e:
                print(f"Error loading face {file_path}: {e}")

load_known_faces()

def recognize_faces(frame):
    try:
        detections = DeepFace.find(img_path=frame, db_path=known_faces_dir, model_name='Facenet', enforce_detection=False)
        if detections and not detections[0].empty:  # Check if the list is non-empty and DataFrame is not empty
            return detections[0].iloc[0]['identity']  # Return the first match
        else:
            return "Unknown"
    except Exception as e:
        print(f"Error during face recognition: {e}")
        return "Error"

def is_face_saved(face_encoding, threshold=0.6):
    """Check if a face encoding is already saved by comparing it to existing encodings."""
    for known_encoding in known_encodings:
        # Compute cosine similarity between the new face and the known faces
        similarity = cosine_similarity([face_encoding], [known_encoding])[0][0]
        if similarity > threshold:
            return True
    return False

# Save the unknown face to the folder
def save_unknown_face(frame):
    try:
        # Extract face encoding
        encoding = DeepFace.represent(img_path=frame, model_name='Facenet')[0]['embedding']

        # Check if face already exists in the folder
        if not is_face_saved(encoding):
            face_filename = f"unknown_faces/unknown_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"
            cv2.imwrite(face_filename, frame)
            print(f"[INFO] Unknown face saved to: {face_filename}")
            known_encodings.append(encoding)  # Add new encoding to the list
        else:
            print(f"[INFO] Duplicate unknown face detected, not saving.")
    except Exception as e:
        print(f"Error saving unknown face: {e}")

# Video threat detection
def process_video_stream(video_source=0):
    cap = cv2.VideoCapture(video_source)
    if not cap.isOpened():
        print("Error: Could not open video stream")
        return

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS)) or 30

    out = None
    recording = False

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Warning: Failed to capture frame, skipping...")
            continue

        # Perform face recognition
        face_result = recognize_faces(frame)
        if face_result == "Unknown":
            print(f"[{datetime.now()}] Unknown face detected!")
            save_unknown_face(frame)

        # Perform object detection
        # Perform object detection
        results = yolo_model.predict(frame, conf=0.5, verbose=False)

        anomalies_detected = False
        if results[0].boxes:
            for box in results[0].boxes:
                # Extract bounding box coordinates
                x1, y1, x2, y2 = map(int, box.xyxy[0].numpy())  # Convert to integers
                cls_id = int(box.cls)
                confidence = box.conf.item()
                label = yolo_model.names[cls_id]

                # Draw bounding box and label on the frame
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 255), 2)  # Red box
                cv2.putText(
                    frame,
                    f"{label} ({confidence:.2f})",
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5,
                    (0, 255, 255),
                    2,
                )  # Yellow label

                print(f"[{datetime.now()}] Detected: {label} (Confidence: {confidence:.2f})")
                if label in ["violence", "weaponized"]:
                    anomalies_detected = True

                    # Start recording if not already recording
                    if not recording:
                        video_filename = f"anomalous_videos/{label}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp4"
                        out = cv2.VideoWriter(video_filename, fourcc, fps, (frame_width, frame_height))
                        recording = True
                        print(f"[{datetime.now()}] Recording started: {video_filename}")

            # Save the annotated frame to the video file if recording
            if recording and out:
                out.write(frame)

        # Stop recording if no anomalies are detected
        if not anomalies_detected and recording:
            print(f"[{datetime.now()}] Anomaly ended. Stopping recording.")
            recording = False
            if out:
                out.release()
                out = None


                if not anomalies_detected and recording:
                    print(f"[{datetime.now()}] Anomaly ended. Stopping recording.")
                    recording = False
                    if out:
                        out.release()
                        out = None

        if cv2.waitKey(1) & 0xFF == ord('q'):
            print("Exit requested. Stopping program.")
            break

    if recording and out:
        out.release()
    cap.release()
    cv2.destroyAllWindows()

# Unified system
def unified_system(video_source=0):
    video_thread = threading.Thread(target=process_video_stream, args=(video_source,))
    audio_thread = threading.Thread(target=process_audio_stream)

    video_thread.start()
    audio_thread.start()

    video_thread.join()
    audio_thread.join()

if __name__ == "__main__":
    unified_system()


[INFO] Starting audio detection thread...
[INFO] Recording audio...
25-01-15 07:34:55 - Searching [[[183 193 197]
  [184 195 200]
  [183 195 201]
  ...
  [156 173 187]
  [157 174 188]
  [158 175 190]]

 [[185 196 199]
  [184 195 200]
  [183 195 201]
  ...
  [155 173 187]
  [157 174 188]
  [158 175 190]]

 [[185 196 199]
  [184 196 199]
  [183 196 199]
  ...
  [155 174 185]
  [157 175 187]
  [157 174 187]]

 ...

 [[198 207 206]
  [197 207 206]
  [194 206 205]
  ...
  [187 193 186]
  [187 193 186]
  [187 193 186]]

 [[198 207 206]
  [198 207 206]
  [198 207 206]
  ...
  [188 193 186]
  [187 193 186]
  [187 193 186]]

 [[200 207 204]
  [199 207 204]
  [198 207 204]
  ...
  [190 193 186]
  [189 193 186]
  [189 193 186]]] in 4 length datastore
25-01-15 07:34:59 - find function duration 4.2825188636779785 seconds
[2025-01-15 07:34:59.858389] Unknown face detected!
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[2025-01-15 07:34:59.991674] Detected audio anomaly: Explosions (Confidence: 0.84)
[INFO] 